apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaim
metadata:
  name: resourceclaim-2nic-4cpu
spec:
  devices:
    requests:
      - name: req-nic
        deviceClassName: dra.net
        count: 2
        selectors:
          - cel:
              # This expression selects devices where the 'rdma' attribute is true.
              expression: device.attributes["dra.net"].rdma == true
      - name: req-cpu
        deviceClassName: dra.cpu
        count: 4
    constraints:
    - matchAttribute: 'dra.net/numaNode'
