apiVersion: v1
kind: Pod
metadata:
  name: my-app-with-dra-cpu
spec:
  containers:
    - name: container1
      image: "registry.k8s.io/pause:3.9"
      resources:
        requests:
          cpu: "4"
        limits:
          cpu: "4"
        claims:
          - name: "container1-claim"
    - name: container2
      image: "registry.k8s.io/pause:3.9"
      resources:
        requests:
          cpu: "6"
        limits:
          cpu: "6"
        claims:
          - name: "container2-claim"
  resourceClaims:
    - name: "container1-claim"
      resourceClaimName: cpu-request-4-cpus
    - name: "container2-claim"
      resourceClaimName: cpu-request-6-cpus
