apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaim
metadata:
  name: cpu-nic-request
spec:
  devices:
    requests:
      # Request for a specific network device (eth1)
      - name: req-nic
        deviceClassName: dranet # The class name for your network driver
        selectors:
          # This CEL expression selects ONLY the device where ifName is 'eth1'
          - cel:
             expression: device.attributes["dra.net"].ifName == "eth1"

      # Request for CPUs
      - name: req-cpu
        deviceClassName: dra.cpu 
        count: 8

   
    constraints:
    - matchAttribute: 'dra.net/numaNode'