apiVersion: v1
kind: Pod
metadata:
  name: my-app-with-dra-cpu
spec:
  containers:
    - name: my-app
      image: "registry.k8s.io/pause:3.9"
      resources:
        requests:
          cpu: "4"
        limits:
          cpu: "4"
        claims:
          - name: "req-dummy"
    - name: my-app-2
      image: "registry.k8s.io/pause:3.9"
      resources:
        requests:
          cpu: "6"
        limits:
          cpu: "6"
        claims:
          - name: "req-dummy-2"
  resourceClaims:
    - name: "req-dummy"
      resourceClaimName: dummy-cpu-request
    - name: "req-dummy-2"
      resourceClaimName: dummy-cpu-request-2