apiVersion: v1
kind: Pod
metadata:
  name: my-app-with-dra-cpu
spec:
  containers:
    - name: container1
      image: "registry.k8s.io/pause:3.9"
      resources:
        requests:
          cpu: "8"
        limits:
          cpu: "8"
        claims:
          - name: "container1-claim"
  resourceClaims:
    - name: "container1-claim"
      resourceClaimName: cpu-nic-request
